### ISSUE TITLE
--resfile option with Protein Seq Des fails to load

### ISSUE THREAD

**Issue by jadolfbr** [RosettaCommons/Rosetta-DL#1]
Leaving this issue here, since there is no issue page on the protein_seq_des main. 

When running with a the --resfile option, the run fails.  Also, the documentation states that it is 0 indexed, but in-code, this is 1 indexed. 

Error message:

```
Traceback (most recent call last):                                                                
  File "/home/ubuntu/protein_seq_des/run.py", line 155, in <module>                               
    main()                                                                                        
  File "/home/ubuntu/protein_seq_des/run.py", line 106, in main
    design_sampler.init_seq()
  File "/home/ubuntu/protein_seq_des/seq_des/sampler.py", line 208, in init_seq
    res, idx, res_label = self.sample(self.logits_temp, np.arange(len(res_label)))
  File "/home/ubuntu/protein_seq_des/seq_des/sampler.py", line 493, in sample
    logits = self.enforce_constraints(logits, idx)
  File "/home/ubuntu/protein_seq_des/seq_des/sampler.py", line 367, in enforce_constraints
    logits = self.enforce_resfile(logits, idx)
  File "/home/ubuntu/protein_seq_des/seq_des/sampler.py", line 362, in enforce_resfile
    logits[i, common.atoms.aa_map_inv[aa]] = -np.inf
TypeError: unhashable type: 'set'
```

Resfile:

```
NATAA
start
163 PIKAA HNRS
164 PIKAA APST
199 PIKAA HLQR
202 PIKAA AGST
```

Command:
` run.py --pdb my.pdb --randomize 1 --log_dir DL --resfile resfile_dl`

**Comment by gelnesr** [comment]
Hi @jadolfbr, 

Sorry for getting back to you so late. We are detaching our repository from the fork so that issues can be submitted directly to our repo. Because of that, we never saw this issue.

The bug you noted has already been fixed in our current version of the repo (found at [protein_seq_des](https://github.com/ProteinDesignLab/protein_seq_des)).  It should hopefully be fixed now. 

Please let me know if you still run into any issues.
